const shopList=[
    {
        type:'主食',
        list:[
            {
                foodName:'米饭',
                price:2,
            },{
                foodName:'小米粥',
                price:3,
            },{
                foodName:'大米粥',
                price:3,
            },{
                foodName:'馒头',
                price:2,
            },{
                foodName:'大饼',
                price:5,
            },{
                foodName:'花卷',
                price:2,
            },
        ]
    },{
        type:'凉菜',
        list:[
            {
                foodName:'拍黄瓜',
                price:13,
            },{
                foodName:'毛豆',
                price:23,
            },{
                foodName:'老虎菜',
                price:15,
            },{
                foodName:'凉皮',
                price:12,
            },{
                foodName:'干豆腐伴黄瓜',
                price:5,
            }
        ]
    },{
        type:'热菜',
        list:[
            {
                foodName:'回锅肉',
                price:44,
            },{
                foodName:'清蒸大闸蟹',
                price:33,
            },{
                foodName:'水煮大闸蟹',
                price:43,
            },{
                foodName:'红烧大闸蟹',
                price:52,
            },{
                foodName:'锅包肉',
                price:35,
            },{
                foodName:'两斤大龙虾',
                price:54,
            }
        ]
    },{
        type:'清凉饮品',
        list:[
            {
                foodName:'杏仁露',
                price:12,
            },{
                foodName:'糖水',
                price:5,
            },{
                foodName:'人奶',
                price:30,
            },{
                foodName:'印度神油',
                price:11,
            },{
                foodName:'冰可乐',
                price:5,
            },{
                foodName:'雪碧',
                price:4,
            }
        ]
    },
]

module.exports = shopList;